// <auto-generated />
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250909160841_E-CommerceNew")]
    partial class ECommerceNew
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("API.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Apple Watch Series 1, temel sağlık ve bildirim takibi özelliklerine sahip, spor ve günlük kullanım odaklı bir akıllı saattir.",
                            IsActive = true,
                            Name = "Apple Watch Series 1",
                            Price = 7000m,
                            Stock = 100
                        },
                        new
                        {
                            Id = 2,
                            Description = "Apple Watch Series 2, daha hızlı bir işlemci ve gelişmiş sağlık izleme özellikleri sunan bir akıllı saattir.",
                            IsActive = true,
                            Name = "Apple Watch Series 2",
                            Price = 15000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 3,
                            Description = "Apple Watch Series 3, suya dayanıklılık ve gelişmiş fitness özellikleri ile donatılmış bir akıllı saattir.",
                            IsActive = true,
                            Name = "Apple Watch Series 3",
                            Price = 20000m,
                            Stock = 300
                        },
                        new
                        {
                            Id = 4,
                            Description = "Xiaomi Redmi Watch 1, uygun fiyatlı bir akıllı saat arayanlar için ideal bir seçenektir.",
                            IsActive = true,
                            Name = "Xiaomi Redmi Watch 1",
                            Price = 3500m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 5,
                            Description = "Xiaomi Redmi Watch 2, daha büyük bir ekran ve geliştirilmiş sağlık izleme özellikleri sunan bir akıllı saattir.",
                            IsActive = true,
                            Name = "Xiaomi Redmi Watch 2",
                            Price = 5000m,
                            Stock = 150
                        },
                        new
                        {
                            Id = 6,
                            Description = "Xiaomi Redmi Watch 3, daha fazla özellik ve şıklık sunan bir akıllı saattir.",
                            IsActive = true,
                            Name = "Xiaomi Redmi Watch 3",
                            Price = 6000m,
                            Stock = 200
                        },
                        new
                        {
                            Id = 7,
                            Description = "Xiaomi Redmi Watch 4, daha fazla özelliği uygun fiyatlı bir akıllı saatte arayanlar için ideal bir seçenektir.",
                            IsActive = true,
                            Name = "Xiaomi Redmi Watch 4",
                            Price = 3500m,
                            Stock = 400
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
